# Generated by Django 5.2 on 2025-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_user_id_alter_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='tag', help_text='Bootstrap icon class name', max_length=30),
        ),
    ]
