# Generated by Django 5.2 on 2025-05-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
